version: '3'
services:
  php8:
    container_name: php8
    build:
      context: ./
    image: php8
    environment:
      - "TIMEZONE=Asia/Shanghai"
      - "APP_PROJECT=php"
      - "APP_SYSTEM_ENV=docker"
    working_dir: "/var/www"
    #    links:
    #      - rabbitmq
    #      - redis
    #      - mongo
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - /www/api/:/var/www
    tty: true
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.27-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: your_username
      RABBITMQ_DEFAULT_PASS: your_password
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    volumes:
      - /www/docker/rabbitmq:/var/lib/rabbitmq

  redis:
    restart: always
    container_name: redis
    image: redis:6.2.6-alpine
    command: ["redis-server", "--requirepass", "your_password"]
    ports:
      - "6379:6379"
    volumes:
      - /www/docker/docker/redis:/var/log/redis/


  mongo:
    container_name: mongo
    image: mongo:4.2.9
    environment:
      # 初始化默认账户&密码
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin@2023
    # 开启安全认证，开放端口
    # --wiredTigerCacheSizeGB=2 限制使用最大内存
    # command: ["--auth"]
    command: ["--port", "27017", "--auth"  , "--wiredTigerCacheSizeGB=2"]
    ports:
      - "27017-27019:27017-27019"
      - "28017:28017"
    volumes:
      - /www/mongo/data:/data/db

  mysql:
    restart: always
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    volumes:
      - D:\WWW\docker\mysql\data:/var/lib/mysql
      - D:\WWW\docker\mysql\my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这
      - D:\WWW\docker\mysql\source:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
      - "3307:3307"
      - "3308:3308"
